apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2025-05-27T16:33:18Z"
  labels:
    app: spring-petclinic-rest
  name: spring-petclinic-rest
  namespace: default
  resourceVersion: "1530"
  uid: 59e29946-c2f8-402b-befa-151153dd6a1e
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.102.2.116
  clusterIPs:
  - 10.102.2.116
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32086
    port: 9966
    protocol: TCP
    targetPort: 9966
  selector:
    app: spring-petclinic-rest
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
